SHOW DATABASES;

CREATE DATABASE TEST;

USE TEST;

CREATE TABLE CUSTOMER
( CUSTOMER_ID INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
MIDDLE_NAME VARCHAR(50),
ADDRESS_LINE1 VARCHAR(80),
ADDRESS_LINE2 VARCHAR(80),
CITY VARCHAR(40),
COUNTRY VARCHAR(50),
DATE_ADDED DATE,
REGION VARCHAR(10));

CREATE TABLE PRODUCT
( PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(100),
STANDARD_COST DECIMAL(10,2),
COLOR VARCHAR(20),
LIST_PRICE DECIMAL(10,2),
PRODUCT_SIZE DECIMAL(8,2),
WEIGHT DECIMAL(10,2),
PRODUCT_CATEGORY VARCHAR(20)
);

CREATE TABLE SALES
( SALES_DATE DATE,
ORDER_ID INT,
PRODUCT_ID INT,
CUSTOMER_ID DECIMAL(5,0),
SALESPERSON_ID DECIMAL(5,0),
QUANTITY DECIMAL(4,0),
UNIT_PRICE DECIMAL(10,2),
SALES_AMOUNT DECIMAL(10,2),
TAX_AMOUNT DECIMAL(10,2),
TOTAL_AMOUNT DECIMAL(10,2)
);

CREATE TABLE SALES_HISTORY
( SALES_DATE DATE,
ORDER_ID INT,
PRODUCT_ID INT,
CUSTOMER_ID DECIMAL(5,0),
SALESPERSON_ID DECIMAL(5,0),
QUANTITY DECIMAL(4,0),
UNIT_PRICE DECIMAL(10,2),
SALES_AMOUNT DECIMAL(10,2),
TAX_AMOUNT DECIMAL(10,2),
TOTAL_AMOUNT DECIMAL(10,2)
);

CREATE TABLE SALESPERSON
( SALESPERSON_ID INT,
JOB_TITLE VARCHAR(80),
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
MIDDLE_NAME VARCHAR(50),
ADDRESS_LINE1 VARCHAR(80),
ADDRESS_LINE2 VARCHAR(80),
CITY VARCHAR(40),
COUNTRY VARCHAR(50),
DATE_ADDED DATE
);

